name: flutter_template
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #State
  provider: ^6.0.5

  #Utils
  get_it: ^7.2.0
  easy_localization: ^3.0.1
  auto_route: ^7.8.4
  equatable: ^2.0.5
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  permission_handler: ^11.0.1 #Ios kurulumları yapılacak.
  envied: ^0.5.3
  easy_logger: ^0.0.2 #EasyLocalization logları için kullanılıyor.
  logger: ^2.0.2+1
  platform_device_id: ^1.0.1
  battery_plus: ^5.0.2
  flutter_udid: ^2.0.1
  package_info_plus: ^5.0.1

  #View
  google_fonts: ^6.1.0
  line_icons: ^2.0.3
  cupertino_icons: ^1.0.2
  lottie: ^3.0.0
  font_awesome_flutter: ^10.7.0

  #Network
  dio: ^5.1.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

  #Google-Firebase
  firebase_core: ^2.8.0
  firebase_messaging: ^14.3.0
  firebase_crashlytics: ^3.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  auto_route_generator: ^7.3.2
  hive_generator: ^2.0.0
  envied_generator: ^0.5.3

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/map_styles/

